import type { Metadata } from "next";
import "@/styles/globals.scss";
import Header from "@/components/header";
import Footer from "@/components/footer";
import GridProvider from "@/providers/GridProvider";
import Spacer from "@/components/ui/spacer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GridProvider>
          <Header />
          {children}
          <Footer />
        </GridProvider>
      </body>
    </html>
  );
}
